spring:
  profiles:
    active:
    - dev
---
spring:
  profiles:
    active: dev
  application:
    name: config-eureka-test
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
---
spring:
  profiles:
    active: test
  application:
    name: config-eureka-test
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka