spring:
  profiles:
    active:
    - dev
---
server:
  port: 7001

spring:
    profiles:
      active: dev
    application:
      name: config-eureka-test

eureka:
  instance:
    hostname: eureka7001.com
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
---
server:
  port: 7001

spring:
    profiles:
      active: test
    application:
      name: config-eureka-test

eureka:
  instance:
    hostname: eureka7001.com
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/